"""init db and create user, link, linc_event table

Revision ID: 8df35b32ba59
Revises: 
Create Date: 2026-03-11 19:20:20.401979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df35b32ba59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('short_code', sa.String(length=12), nullable=False),
    sa.Column('custom_alias', sa.String(length=50), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_clicked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('clicks_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_alias')
    )
    op.create_index('ix_links_active_expiration', 'links', ['is_active', 'expires_at'], unique=False)
    op.create_index(op.f('ix_links_created_at'), 'links', ['created_at'], unique=False)
    op.create_index(op.f('ix_links_expires_at'), 'links', ['expires_at'], unique=False)
    op.create_index(op.f('ix_links_is_active'), 'links', ['is_active'], unique=False)
    op.create_index(op.f('ix_links_last_clicked_at'), 'links', ['last_clicked_at'], unique=False)
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    op.create_index('ix_links_user_active', 'links', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_links_user_id'), 'links', ['user_id'], unique=False)
    op.create_table('click_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_created_at'), 'click_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_click_events_device_type'), 'click_events', ['device_type'], unique=False)
    op.create_index(op.f('ix_click_events_ip_address'), 'click_events', ['ip_address'], unique=False)
    op.create_index(op.f('ix_click_events_link_id'), 'click_events', ['link_id'], unique=False)
    op.create_index('ix_clicks_country_created', 'click_events', ['country_code', 'created_at'], unique=False)
    op.create_index('ix_clicks_device_created', 'click_events', ['device_type', 'created_at'], unique=False)
    op.create_index('ix_clicks_link_created', 'click_events', ['link_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clicks_link_created', table_name='click_events')
    op.drop_index('ix_clicks_device_created', table_name='click_events')
    op.drop_index('ix_clicks_country_created', table_name='click_events')
    op.drop_index(op.f('ix_click_events_link_id'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_ip_address'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_device_type'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_created_at'), table_name='click_events')
    op.drop_table('click_events')
    op.drop_index(op.f('ix_links_user_id'), table_name='links')
    op.drop_index('ix_links_user_active', table_name='links')
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.drop_index(op.f('ix_links_last_clicked_at'), table_name='links')
    op.drop_index(op.f('ix_links_is_active'), table_name='links')
    op.drop_index(op.f('ix_links_expires_at'), table_name='links')
    op.drop_index(op.f('ix_links_created_at'), table_name='links')
    op.drop_index('ix_links_active_expiration', table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
